# Generated by Django 3.1 on 2020-08-08 07:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Naver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome do Naver', models.CharField(max_length=50)),
                ('Data de Nascimento', models.DateField()),
                ('Data de Admissão na Empresa', models.DateField()),
                ('job_role', models.CharField(choices=[('DEV', 'Desenvolvedor'), ('DES', 'Designer'), ('UXD', 'Designer de UX')], max_length=10, verbose_name='Cargo do naver')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email do Usuário', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrição do Projeto', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('naver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nave.naver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nave.user')),
            ],
        ),
        migrations.AddField(
            model_name='naver',
            name='projects',
            field=models.ManyToManyField(through='nave.Project', to='nave.User'),
        ),
    ]
